# Generated by Django 4.0.3 on 2022-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='binhluan',
            fields=[
                ('maBL', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('binhluan', models.TextField(max_length=500)),
                ('thoigian', models.DateField(max_length=100)),
                ('maSP', models.CharField(max_length=10)),
                ('trangthaiBL', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'binhluan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='chitietdonhang',
            fields=[
                ('STT', models.AutoField(primary_key=True, serialize=False)),
                ('maKH', models.CharField(max_length=10)),
                ('maSP', models.CharField(max_length=10)),
                ('dongia', models.FloatField(max_length=100)),
                ('soluong', models.CharField(max_length=10)),
                ('HD', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'chitietdonhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='donhang',
            fields=[
                ('maDH', models.AutoField(primary_key=True, serialize=False)),
                ('maKH', models.CharField(max_length=10)),
                ('maNV', models.CharField(max_length=10)),
                ('trangthaiDH', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'donhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='giohang',
            fields=[
                ('STT', models.AutoField(primary_key=True, serialize=False)),
                ('maKH', models.CharField(max_length=10)),
                ('maSP', models.CharField(max_length=10)),
                ('soluong', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'giohang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='khachhan',
            fields=[
                ('maKH', models.AutoField(primary_key=True, serialize=False)),
                ('tenKH', models.CharField(max_length=100)),
                ('ngaysinhKH', models.DateField(max_length=500, null=True)),
                ('gioitinhKH', models.CharField(max_length=8)),
                ('sdtKH', models.CharField(max_length=11)),
                ('emailKH', models.CharField(max_length=500)),
                ('diachiKH', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'khachhan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='loaisanpham',
            fields=[
                ('maloaiSP', models.AutoField(primary_key=True, serialize=False)),
                ('tenloaiSP', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'loaisanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='nhanvien',
            fields=[
                ('maNV', models.AutoField(primary_key=True, serialize=False)),
                ('tenNV', models.CharField(max_length=100)),
                ('emailNV', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=8)),
                ('sdtNV', models.CharField(max_length=11)),
                ('diachiNV', models.CharField(max_length=500)),
                ('tinhtrangVN', models.CharField(max_length=50)),
                ('chucvuNV', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('maSP', models.AutoField(primary_key=True, serialize=False)),
                ('tenSP', models.CharField(max_length=100)),
                ('Hinh', models.ImageField(upload_to='assets/img/')),
                ('giaSP', models.CharField(max_length=8)),
                ('soluongSP', models.CharField(max_length=11)),
                ('motaSP', models.TextField(max_length=500)),
                ('maloaiSP', models.CharField(max_length=500)),
                ('thuonghieu', models.CharField(max_length=50)),
                ('quocgia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='taikhoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tinhtrangTK', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='thuonghieu',
            fields=[
                ('maTH', models.AutoField(primary_key=True, serialize=False)),
                ('tenTH', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'thuonghieu',
                'managed': False,
            },
        ),
    ]
